export default {
  SET_COOKIE: 'SET_COOKIE',
  REMOVE_COOKIE: 'REMOVE_COOKIE',

  SET_API_ENGINE: 'SET_API_ENGINE',

  SET_TODO: 'SET_TODO',
  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',

  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',

  UPDATE_LOCALE: 'UPDATE_LOCALE',

  SET_POSTS: 'SET_POSTS',
  SET_POST: 'SET_POST',
  SET_PAGE: 'SET_PAGE',
};
